### ISSUE TITLE
Failed to load desired amount of users

### ISSUE THREAD

**Issue by Marow** [InstaPy/InstaPy#2252]
I get this:

```
INFO [2018-06-15 10:03:01] [************]  Failed to load desired amount of users
INFO [2018-06-15 10:03:01] [************]  Simulated follow : 1
Traceback (most recent call last):
  File "quickstart.py", line 60, in <module>
    session.follow_user_followers(accs, amount=20, randomize=True, sleep_delay=20)
  File "/var/www/instapy/InstaPy/instapy/instapy.py", line 1929, in follow_user_followers
    self.logfolder)
  File "/var/www/instapy/InstaPy/instapy/unfollow_util.py", line 766, in get_given_user_followers
    logger, logfolder)
  File "/var/www/instapy/InstaPy/instapy/unfollow_util.py", line 590, in get_users_through_dialog
    quick_index = random.randint(0, len(follow_buttons)-1)
  File "/usr/lib/python2.7/random.py", line 242, in randint
    return self.randrange(a, b+1)
  File "/usr/lib/python2.7/random.py", line 218, in randrange
    raise ValueError, "empty range for randrange() (%d,%d, %d)" % (istart, istop, width)
ValueError: empty range for randrange() (0,0, 0)
```

But why? 
I only use that:

`session.follow_user_followers(accs, amount=20, randomize=True, sleep_delay=20)`

Using that on ubuntu server. Newest Version. Downloaded instapy before 2 days....

**Comment by Marow** [comment]
Is that cause the user has to much followers or something?

**Comment by Marow** [comment]
Okay, very crazy... if i choose another account than i want, than its working...
wtf... after some hours, other is also not working

**Comment by uluQulu** [comment]
@Marow 
That error is solved, get the latest files. It will not crash again.

But if you get
```powershell
Failed to load desired amount of users
```
continiously on accaunt with followers more than the amount you have requested, then there is a problem.

**Comment by ArdySan2012** [comment]
I am getting this one as well @uluQulu  it is almost always "Failed to get the desired amount of users" and it is doing only 12/12.   Sometimes it does more, but...

**Comment by Tachenz** [comment]
Joining the club of Those Failed to load desired amount of users...

Does anyone know if there is maybe a way to slow down a scrolling process with sleep delay, not to get “scroll banned” ?

**Comment by Tachenz** [comment]
It is really random. I just restarted bot 6 times within 5 minutes. And for the same user it was:
3 times - Failed to load desired amount of users, starting 1/12
1 time - Failed to load - but 1/150
And 2 times - 1/150 (so requested 150 users loaded with no problem).

So if it is due to Insta protection, it definitely does not last. Meaning, maybe it would be possible just “try again” if failed, or at least sleep for 10 seconds and try again and then move on to interact with whoever got loaded?

Summoning @uluQulu magic :))

**Comment by Tachenz** [comment]
I still get that annoying "grabbed 0 users to interact" with the latest build...

**Comment by Tachenz** [comment]
Nothin stale there unfortunately :D
