### ISSUE TITLE
How to update instapy

### ISSUE THREAD

**Issue by emyabdel** [InstaPy/InstaPy#2753]
Hello

I want to update instapy. I used google and find many ways but i'm really newbie I need a clear step by step.

I'm running it under windows 10. 
what I did:
I installed git bash
I go to instapy folder
right click
git bash here

I type:
git pull origin master
 or
 git pull 

instapy isn't updated and i get this message:
fatal: not a git repository (or any of the parent directories): .git

I really need the easiest way to update explained step by step because i'm really newbie

**Comment by cool-acid** [comment]
You need to make sure you are in the folder where the code is.

**Comment by emyabdel** [comment]
i go to instapy master / instapy
where should i go?

**Comment by narchiii** [comment]
First, try running 
$git init

**Comment by Mehran** [comment]
@emyabdel  to make it easy you can use my script , go to your instapy folder , 
`curl -s https://gist.githubusercontent.com/Mehran/7ddb2848c2abe9ef475b79175f1b605d/raw/86a5e5912160d1455db003244b305c04f411908f/git-update.sh | sh`

Done !

**Comment by emyabdel** [comment]
@Mehran I run the script and I get this message: no update needed
I'm sure that I dont have the latest update because I didn't use instapy since I think 4 months.
where can I check current instapy version that I have and where can I check the latest instapy version?

**Comment by c0d3x27** [comment]
@emyabdel why you keep question question and opening issue then when you get the answers, you dont close the threads? i gave you the answer for the LIKES AND FOLLOW delays you wanted/asked for and you still have the issue open?

**Comment by emyabdel** [comment]
Simply because I didn't get an answer that worked for me!!!

**Comment by c0d3x27** [comment]
@emyabdel what fuck you mean? many people used their time and efford to solve that and solved it. so what do you mean it didnt work for you? you should say "i dont know how to make it work me" and that will be very different. at least you should start closing these issues you keep opening all over the place for nothing.

**Comment by c0d3x27** [comment]
just as you are doing here. you are asking the most silly and noobs questions when you dont need to. the rules are that after you get the help you are looking, you closed the issues. dont just leave it open. just making more confusion.
