### ISSUE TITLE
Recurring SyntaxError: Unexpected identifier error

### ISSUE THREAD

**Issue by dakshshah96** [InstaPy/InstaPy#293]
I've been noticing since the past week that each time I start InstaPy, it works fine for a while (maybe an hour or so, going through 3-4 of the tags) and then abruptly stops with a `SyntaxError: Unexpected identifier` error. Here's a screenshot for reference.
<img width="682" alt="screenshot 2017-06-03 18 23 45" src="https://cloud.githubusercontent.com/assets/7896438/26754801/fc405a30-4889-11e7-82af-323557df1a2c.png">

**Comment by ghost** [comment]
@dakshshah96 I've been experiencing the same error. I made changes to my script particularly using clarifai so I have reverted today to see if the error will continue. Will update tonight.

**Comment by dakshshah96** [comment]
@imakethefish Any luck on fixing the error?

**Comment by razvanilin** [comment]
I get the same error at random times

**Comment by ghost** [comment]
@dakshshah96 at first I changed my clarifai settings and it appeared to work. However, it has continued again this week. 

It appears to only happen on certain hashtags. Have you had any luck?

Maybe post your code so we can compare?

**Comment by razvanilin** [comment]
I removed clarifai and it still happens. Seems to be happening more often than ever now. The script rarely manages to reach the second hashtag.

**Comment by razvanilin** [comment]
So this is definitely caused by the commenting function, as the error specifies. Disabling the comment feature will make the script work.

**Comment by timgrossmann** [comment]
@dakshshah96 @imakethefish @razvanilin 
Can anyone submit a Fix for this?

**Comment by diveu** [comment]
@timgrossmann Had the same issue. It was the \' symbol, which was set as ' in js code and it caused the string to exit early, so the <Unexpected identifier> error occured. I think you could solve it by simply escaping the ' symbol with another backslash.
For example:
'that\'s nice!' - this one causes an error once it gets to comments.
'that\\\'s nice!' - should work out just fine.
I tested it just in browser console and it worked, but i think this should fix it in comment section.

**Comment by timgrossmann** [comment]
@diveu If that really is the case, then this issue has nothing to do with InstaPy....
Thank you!

**Comment by razvanilin** [comment]
I don't think that's the issue. I had all the comments escaped in my script and it was still throwing the error randomly. I double-checked the comments again and they are all escaped properly.

I removed the `'` from my comments and see if that's causing the error

**Comment by diveu** [comment]
@razvanilin yeah, I'm saying it based on removal of `'` character from my comments. And it got the script running the whole day perfectly. Let's see how it works on your side :)

**Comment by razvanilin** [comment]
got you

The script seems to be working fine for me too. Before, it used to crash after a few comments (probably when encountering one with `'`)
