### ISSUE TITLE
"Failed to get likers count on your post" I think the xpath has changed.

### ISSUE THREAD

**Issue by sionking** [InstaPy/InstaPy#3059]
Can someone fix it ?

**Comment by sebastian-ardila** [comment]
I have the same problem, before the class of the likers button was zV_Nj, i guess it was from the likes button, but now there are several class name in there class="oF4XW sqdOP yWX7d    _8A5w5", i replace zV_Nj of util.py for each one of those class names but none of those worked for me, so i don't know if that is the correct element

**Comment by cmaixen** [comment]
Hi I fixed it ! 

change line 308 to        


```
likers_count = (browser.find_element_by_xpath(
                        "//button[contains(@class, '_8A5w5')]/span").text) 
```

and line 319 to   


```
browser.find_elements_by_xpath(
                "//button[contains(@class, '_8A5w5')]")[1].click()
```

**Comment by sebastian-ardila** [comment]
Excelent @cmaixen i think you have other version different i have, but in summary it's just replacing the class **zV_Nj** for the class **_8A5w5** in all lines the class appear, and replace in the same lines the tag **a** for the tag **button**, in my case the lines were **319** and **330**

edit:
i just noticed the error dissapeared but the function does'nt return the active followers

**Comment by sebastian-ardila** [comment]
> Hi I fixed it !
> 
> change line 308 to
> 
> ```
> likers_count = (browser.find_element_by_xpath(
>                         "//button[contains(@class, '_8A5w5')]/span").text) 
> ```
> and line 319 to
> 
> ```
> browser.find_elements_by_xpath(
>                 "//button[contains(@class, '_8A5w5')]")[1].click()
> ```

the line 319 crash when it's trying to count likers of videos

**Comment by manzoo-dev** [comment]
Facing same issue. tried a few things with the class names, but still no luck. I Better take a fresh pull and redo, as my code is a mess.

**Comment by fgisslen** [comment]
same problem here with videos

**Comment by booksix** [comment]
Same problem - also when looking at videos...

... `in get_active_users`
`"//button[contains(@class, '_8A5w5')]")[1]`
`IndexError: list index out of range`

**Comment by danialmoghaddam** [comment]
Same problem

`File "/home/ubuntu/InstaPy/instapy/util.py", line 434, in get_active_users
    "//button[contains(@class, '_8A5w5')]")[1]
IndexError: list index out of range`

**Comment by manzoo-dev** [comment]
I guess somebody fixed it, i took a pull last week and seems to be working fine now. Havent had the time to check the fix , but whoever did it, great job mate.. :)

**Comment by converge** [comment]
Inactive issue, reopen if you need assistance.
