### ISSUE TITLE
LIKE ELEMENT HAS CHANGED FOR 20% of users.

### ISSUE THREAD

**Issue by sionking** [InstaPy/InstaPy#3075]
I see that like is failing (not clicking) for 10-20% of users. a/b testing.
Can someone confirm ?

**Comment by Tachenz** [comment]
Yes, sometimes I get an error saying "like element not found", but most of the times I don't...

**Comment by sionking** [comment]
is it something new ?

**Comment by simonecorsi** [comment]
I'm having the same problem since nearly a week, at first I thought it was some sort of soft ban, but it was unlikely since follow/defollow was working and there is no error.

I'm running a [modified instapy](https://github.com/Kirkhammetz/InstaPy) that spin multiple bots which exits from the same VPS, thought it was some sort of soft ban so I've implemented proxies but it's only one or 2 account affected.

If there is something I can do to help troubleshoot just let me know.

**Comment by Tachenz** [comment]
@sionking
It is new, yes.
For the same user, just right now - image 1 “Image was not able to get liked. invalid like element”
But then image 2 and 3 (I run 3 images per user) - are liked alright.

**Comment by sionking** [comment]
maybe structure changed when no comments ?

**Comment by anitato** [comment]
I am also getting this "--> Invalid Like Element!" problem where InstaPy just doesn't like any photos. It doesn't appear to be a ban because I can like manually on my phone app, and follow/unfollow still works. I just updated today to the newest version of InstaPy, so the problem still exists.

edit: Upon further investigation. It does seem to like the RARE occasional post when headless_browser=False. But when I run this on a server with headless_brower=True, InstaPy will say "--> Image Liked!" but that doesn't show up on my "Posts You've Liked" page. So something is not registering between InstaPy (which says things are being liked sometimes, but not all the time) and my actual Instagram account's likes?

**Comment by jeremycjang** [comment]
I can confirm this as well; seems to be mixed. The program will successfully like several photos, but then will start throwing that error  for others. I'm currently observing it in a seemingly random sequence (running *with* GUI).

Perhaps Instagram has changed something or loads the like element in differentially now for whatever reason?

**Comment by lucaceriani** [comment]
I confirm every 2-3 photos i get this issue
