### ISSUE TITLE
ImportError: No module named pyvirtualdisplay

### ISSUE THREAD

**Issue by ghost** [InstaPy/InstaPy#311]
No errors on install, added the nogui tag. What am i doin wrong? 
Thanks guys

`Traceback (most recent call last):
  File "quickstart.py", line 1, in <module>
    from instapy import InstaPy
  File "/home/be-lost/InstaPy/instapy/__init__.py", line 1, in <module>
    from .instapy import InstaPy
  File "/home/be-lost/InstaPy/instapy/instapy.py", line 5, in <module>
    from pyvirtualdisplay import Display
ImportError: No module named pyvirtualdisplay
`

Running it on a DO droplet, 1gb / 30gb

**Comment by timgrossmann** [comment]
@ohoscar Did you follow the instructions on the How_to?
How do you start the script? `python quickstart.py` or `python3 quickstart.py` ?

Do `pip list` and check ich pyvirtualdisplay is in there.
Try to install it by hand: `pip3 install pyvirtualdisplay`

**Comment by ghost** [comment]
i start with python quickstart.py
PyVirtualDisplay (0.2.1) is present. 
I used python3.5 next, this is what i got now. 
`be-lost@box:~/InstaPy$ python3.5 quickstart.py 
Traceback (most recent call last):
  File "quickstart.py", line 5, in <module>
    session = InstaPy(username='xxxxx', password='xxxx', nogui='True')
  File "/home/be-lost/InstaPy/instapy/instapy.py", line 38, in __init__
    self.browser = webdriver.Chrome('./assets/chromedriver', chrome_options=chrome_options)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/chrome/webdriver.py", line 62, in __init__
    self.service.start()
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/common/service.py", line 92, in start
    raise WebDriverException("Can not connect to the Service %s" % self.path)
selenium.common.exceptions.WebDriverException: Message: Can not connect to the Service ./assets/chromedriver
`

**Comment by dmitriiweb** [comment]
> Make sure to get the right chromedriver for your system from https://sites.google.com/a/chromium.org/chromedriver/downloads . Just put it in /assets.

**Comment by ghost** [comment]
I did. 
Its a x64 arch. I still get this error. 


`be-lost@box:~/InstaPy/assets$ uname -a  
Linux box.be-lost.com 4.4.0-78-generic #99-Ubuntu SMP Thu Apr 27 15:29:09 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
be-lost@box:~/InstaPy/assets$ sudo wget https://chromedriver.storage.googleapis.com/2.30/chromedriver_linux64.zip
[sudo] password for be-lost: 
--2017-06-15 10:26:10--  https://chromedriver.storage.googleapis.com/2.30/chromedriver_linux64.zip
Resolving chromedriver.storage.googleapis.com (chromedriver.storage.googleapis.com)... 172.217.6.80, 2607:f8b0:4005:80a::2010
Connecting to chromedriver.storage.googleapis.com (chromedriver.storage.googleapis.com)|172.217.6.80|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3864914 (3.7M) [application/zip]
Saving to: ‘chromedriver_linux64.zip’

chromedriver_linux64.zip             100%[=====================================================================>]   3.69M  --.-KB/s    in 0.04s   

2017-06-15 10:26:10 (102 MB/s) - ‘chromedriver_linux64.zip’ saved [3864914/3864914]

be-lost@box:~/InstaPy/assets$ ls
chromedriver  chromedriver_linux64.zip	unicodes.md
be-lost@box:~/InstaPy/assets$ unzip chromedriver_linux64.zip 
Archive:  chromedriver_linux64.zip
replace chromedriver? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
  inflating: chromedriver            
be-lost@box:~/InstaPy/assets$ ls
chromedriver  chromedriver_linux64.zip	unicodes.md
be-lost@box:~/InstaPy/assets$ cd ..
be-lost@box:~/InstaPy$ python3.5 quickstart.py
Traceback (most recent call last):
  File "quickstart.py", line 5, in <module>
    session = InstaPy(username='xxxx', password='xxxx', nogui='True')
  File "/home/be-lost/InstaPy/instapy/instapy.py", line 38, in __init__
    self.browser = webdriver.Chrome('./assets/chromedriver', chrome_options=chrome_options)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/chrome/webdriver.py", line 62, in __init__
    self.service.start()
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/common/service.py", line 92, in start
    raise WebDriverException("Can not connect to the Service %s" % self.path)
selenium.common.exceptions.WebDriverException: Message: Can not connect to the Service ./assets/chromedriver

`

**Comment by timgrossmann** [comment]
@ohoscar Do you have the nogui Flag set?

`InstaPy(username="", password="", nogui=True)`

**Comment by dmitriiweb** [comment]
@ohoscar 
Install chromedriver from AUR
replace 
`self.browser = webdriver.Chrome('./assets/chromedriver', chrome_options=chrome_options)`
to
`self.browser = webdriver.Chrome(chrome_options=chrome_options)`
in instapy/instapy.py (line#38)

**Comment by FBosler** [comment]
for me this was solved by:
1. checking my python 3 version like this: `python3 --version` (returned 3.5.2)
2. doing `pip3 freeze` to see if pyvirtualdisplay was among my installed packages
3. running my script with `python3.5 myscript.py` (3.5 because it was the major release of the python 3 version on my system - see step 1)

**Comment by timgrossmann** [comment]
@ohoscar And make sure to use python3 instead of 2

**Comment by ghost** [comment]
I faced the same problem. Now I'm getting this error: 

``ubuntu@ip-172-31-21-156:~/scripts/InstaPy$ python3 quickstart.py 
Traceback (most recent call last):
  File "quickstart.py", line 14, in <module>
    InstaPy(username="faiz.png", password="*****", nogui=True) \
  File "/home/ubuntu/scripts/InstaPy/instapy/instapy.py", line 44, in __init__
    self.browser = webdriver.Chrome(chromedriver_location, chrome_options=chrome_options)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/chrome/webdriver.py", line 69, in __init__
    desired_capabilities=desired_capabilities)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 90, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 177, in start_session
    response = self.execute(Command.NEW_SESSION, capabilities)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Driver info: chromedriver=2.29.461571 (8a88bbe0775e2a23afda0ceaf2ef7ee74e822cc5),platform=Linux 4.4.0-79-generic x86_64``

**Comment by dmitriiweb** [comment]
@Faiz7412 
Install chrome driver: https://gist.github.com/ziadoz/3e8ab7e944d02fe872c3454d17af31a5
and 
replace
`self.browser = webdriver.Chrome('./assets/chromedriver', chrome_options=chrome_options)`
to
`self.browser = webdriver.Chrome(chrome_options=chrome_options)`
in instapy/instapy.py (line#38)

**Comment by ghost** [comment]
@dmitriiweb I tried that, ran the script at https://gist.github.com/ziadoz/3e8ab7e944d02fe872c3454d17af31a5 and replaced the line in instapy.py 
I am still getting the same error.
Edit: I tried rebooting the aws instance. Still doesn't solve it.

``ubuntu@ip-172-31-21-156:~/scripts/InstaPy$ python3 quickstart.py 
Traceback (most recent call last):
  File "quickstart.py", line 14, in <module>
    InstaPy(username="faiz.png", password="mypassword", nogui=True) \
  File "/home/ubuntu/scripts/InstaPy/instapy/instapy.py", line 44, in __init__
    self.browser = webdriver.Chrome(chrome_options=chrome_options)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/chrome/webdriver.py", line 69, in __init__
    desired_capabilities=desired_capabilities)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 90, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 177, in start_session
    response = self.execute(Command.NEW_SESSION, capabilities)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Driver info: chromedriver=2.27.440175 (9bc1d90b8bfa4dd181fbbf769a5eb5e575574320),platform=Linux 4.4.0-83-generic x86_64``

**Comment by dmitriiweb** [comment]
@Faiz7412 Do you have chrome browser?

**Comment by ghost** [comment]
![screen shot 2017-07-10 at 3 17 05 pm](https://user-images.githubusercontent.com/8874731/28012281-eb192500-6582-11e7-973f-9fdc95f4879b.png)
As you can see, the script installed chrome on aws server.

**Comment by dmitriiweb** [comment]
@Faiz7412 use phantomjs instead of chrome

**Comment by ghost** [comment]
Okay, but I'd like to see if I can get chrome working for me. @timgrossmann Do you have any suggestions?

**Comment by dmitriiweb** [comment]
@Faiz7412 For this you should install DE on your server, coz Chrome web browser is GUI application.

**Comment by ghost** [comment]
well, I can see that it installed xvfb which can run chrome in terminal. 
I deleted the entire aws instance completely to clear the clutter. Thanks anyway!

**Comment by pyrenecom** [comment]
did you solve your import error? if yes.. how did you fixed?

**Comment by converge** [comment]
pip install pyvirtualdisplay
or
pip3 install ...
or pip3.4 or 3.5
depends on your python version

**Comment by pyrenecom** [comment]
Fixed thanks!
