### ISSUE TITLE
Can Mobile Emulation save Instapy?

### ISSUE THREAD

**Issue by Tachenz** [InstaPy/InstaPy#4641]
So as can be seen from https://github.com/timgrossmann/InstaPy/issues/4595 and other threads Instagram has put Instapy out of business for good...

Regardless of the speed, somehow they figure out the script really fast now (be that liking just once an hour, Firefox or Chrome, changing IPs, etc.), while mobile activity does not seem to be impacted.

The question here is if using chrome mobile emulation could help here?
And is there anyone to tell me how do I test it properly :)

**Comment by GitNees** [comment]
Still works fine

My session just finished without issues, I fixed it by deleting login cookie.

**Comment by riccardovalente** [comment]
> So as can be seen from #4595 and other threads Instagram has put Instapy out of business for good...

I'm not sure that is actually the case. Although I've had bans in the past, my main accounts have been chugging along nicely for weeks, possibly (but who knows??) because of the low peak rates, very few accounts, randomise everything, and using a residential IP address (i.e. no datacentres involved). 

Mobile emulation *may* help, but who does genuine Instagram work from a web browser on their phones, instead of using the app? My guess is that this will be flagged as "botty" just the same, and throttled right down.

**Comment by ghost** [comment]
I hope to be wrong, but it looks like that we will get used to quit InstaPy...

**Comment by KeenonT** [comment]
Has been working fine for me as well. Unrelated issues with the latest update but I haven't been banned so far. 

Mild settings on quota supervisor
randomized action delays
mild like/follow/commenting ratios..

so far so good.

**Comment by Tachenz** [comment]
@intellem0s could you please share likes/follows per hour (on average) you are doing it at?

While some are not affected, many are. And for those who are - mobile apps are still functional, while browser activity is not...

**Comment by KeenonT** [comment]
i have it running every 4 hours. in each session in averages about

likes: 190-210
comments: 30-50 (i play with these percentages too often for a more concrete grasp)
follow: 40-60
unfollow: 30, slowly raising these but that's been working out so far. fingers crossed

**Comment by ghost** [comment]
> i have it running every 4 hours. in each session in averages about
> 
> likes: 190-210
> comments: 30-50 (i play with these percentages too often for a more concrete grasp)
> follow: 40-60
> unfollow: 30, slowly raising these but that's been working out so far. fingers crossed

Mine are way far less aggressive but I am blocked from any actions.

**Comment by KeenonT** [comment]
> > i have it running every 4 hours. in each session in averages about
> > likes: 190-210
> > comments: 30-50 (i play with these percentages too often for a more concrete grasp)
> > follow: 40-60
> > unfollow: 30, slowly raising these but that's been working out so far. fingers crossed
> 
> Mine are way far less aggressive but I am blocked from any actions.

that scares me. i'll go a more modest route

**Comment by sionking** [comment]
[assets.zip](https://github.com/timgrossmann/InstaPy/files/3376063/assets.zip)
please try with this chromedriver and non headless

**Comment by kwstasna** [comment]
> [assets.zip](https://github.com/timgrossmann/InstaPy/files/3376063/assets.zip)
> please try with this chromedriver and non headless

what is this?

**Comment by Tr1pke** [comment]
I don't think headless makes such a difference

**Comment by sionking** [comment]
> I don't think headless makes such a difference

please don't think.
Test, ask, check, study.
HEADLESS IS SUPER DETECTABLE!
I have only 15% follow blocks on my instapy accounts.

**Comment by sionking** [comment]
> > [assets.zip](https://github.com/timgrossmann/InstaPy/files/3376063/assets.zip)
> > please try with this chromedriver and non headless
> 
> what is this?

chromedriver modifided.

**Comment by ktconsidine** [comment]
@sionking Thanks - can you advise how to use the modified chromedriver?

**Comment by kwstasna** [comment]
@sionking yeah man obviously we can understand this, but what has been modified ???

**Comment by ktconsidine** [comment]
@sionking in my question I actually mean where do I specifically place the new chromedriver? (Windows 10) I popped file into C:\Users\KTC\InstaPy\assets but still immediately "like blocked" with non-headless browser. Does the new driver instead need to go somewhere related to C:\Users\KTC\AppData\Local\Programs\Python\Python37-32\lib\site-packages\instapy ?

Thank you for your review and time.

**Comment by yoannes** [comment]
> [assets.zip](https://github.com/timgrossmann/InstaPy/files/3376063/assets.zip)
> please try with this chromedriver and non headless

I tried the modified chromedriver and so far it's working fine, I stopped for today and will try again tomorrow.. For the last two weeks I was not even able to like this many pictures without getting blocked

        |> LIKED 26 images  |  ALREADY LIKED: 2
        |> COMMENTED on 0 images
        |> FOLLOWED 0 users  |  ALREADY FOLLOWED: 0
        |> UNFOLLOWED 0 users
        |> LIKED 0 comments
        |> REPLIED to 0 comments
        |> INAPPROPRIATE images: 0
        |> NOT VALID users: 38

**Comment by Tachenz** [comment]
Yes, where do we put it in? :) For rookies... I mean - new chromedriver (to be sure it still does not use the old one)

**Comment by ghost** [comment]
> [assets.zip](https://github.com/timgrossmann/InstaPy/files/3376063/assets.zip)
> please try with this chromedriver and non headless

Thanks for your help.
I have just tried but unfortunately it does not work. I run chromedriver75 file and I got blocked to like.
Very sad.

Just a note: I see through the browser that bot likes a pictures, the terminal shows "Image liked" but immediately after that like is being deleted and the terminal windows shows the fu***ing sentence: "... you have BLOCK on likes".

Really disappointing...

**Comment by ghost** [comment]
> Yes, where do we put it in? :) For rookies... I mean - new chromedriver (to be sure it still does not use the old one)

For Windows users:
1) put chromedriver (73 or 75 exe files based on your Chrome version) file provided at this location:  **C:\users\your-pc-username\InstaPy\assets**
2) open file "settings.py" which is located here: **C:\Program Files\Python\Python36\Lib\site-packages\instapy**
3) insert a new row at 37 with this: `chromedriver_location = "C:/users/your-pc-username/InstaPy/assets/chromedriver"`
4) comment out this: `chromedriver_location = localize_path("assets", specific_chromedriver)`

That's it.

**Comment by ktconsidine** [comment]
Thank you @RRphoto - I was able to make the edits with modified chromedriver in place. That said, I am still ACTION BLOCKED upon very first attempt on running instapy thereafter to LIKE images.

Who is still running instapy successfully and how? I never use the follow/unfollow actions and was using it to perform LIKE actions on a specific list of users to free up my time. Really bummed to lose my instapy functionality completely.

**Comment by sionking** [comment]
> Thank you @RRphoto - I was able to make the edits with modified chromedriver in place. That said, I am still ACTION BLOCKED upon very first attempt on running instapy thereafter to LIKE images.
> 
> Who is still running instapy successfully and how? I never use the follow/unfollow actions and was using it to perform LIKE actions on a specific list of users to free up my time. Really bummed to lose my instapy functionality completely.

You can just remove old one and put the new one in the asset folder, jsut rename it (remove the 73/75 at the end). remove cookies (in logs folder) don't go headless, and try again.

**Comment by rvoets** [comment]
@sionking for me it's working again using your driver. Thanks a lot. Do you also have a driver for mac?

**Comment by ghost** [comment]
> @sionking for me it's working again using your driver. Thanks a lot. Do you also have a driver for mac?

Did you run more times consecutively? What are your settings in `quickstart.py` file?

**Comment by rvoets** [comment]
Two 4 hour runs of > 400 likes each and > 50 follows and > 50 comments. I deleted the cookie and randomized the delays of likes, follows and comments.

**Comment by yoannes** [comment]
> Two 4 hour runs of > 400 likes each and > 50 follows and > 50 comments. I deleted the cookie and randomized the delays of likes, follows and comments.

I also radomzied the delays on likes and seemed to make some difference

**Comment by Good-Kat** [comment]
What to do on unix server ? We can't use headless=false
is there a version of the chromedriver for unix ? as mentioned is for windows

**Comment by Tr1pke** [comment]
> What to do on unix server ? We can't use headless=false
> is there a version of the chromedriver for unix ? as mentioned is for windows



> What to do on unix server ? We can't use headless=false
> is there a version of the chromedriver for unix ? as mentioned is for windows

Vnc

**Comment by jtrieuDev** [comment]
Hi, i tried to delete the cookie file, but after one session, i cannot find it again and delete it, why ?

**Comment by ghost** [comment]
> > What to do on unix server ? We can't use headless=false
> > is there a version of the chromedriver for unix ? as mentioned is for windows
> 
> > What to do on unix server ? We can't use headless=false
> > is there a version of the chromedriver for unix ? as mentioned is for windows
> 
> Vnc

He (also) asked for a Unix version of chromedriver file. Furthermore, VNC is only a viewer and if the Unix server is a non-GUI version, like Ubuntu Server or CentOS, VNC is completely unuseful.

**Comment by Tr1pke** [comment]
> > > What to do on unix server ? We can't use headless=false
> > > is there a version of the chromedriver for unix ? as mentioned is for windows
> > 
> > 
> > > What to do on unix server ? We can't use headless=false
> > > is there a version of the chromedriver for unix ? as mentioned is for windows
> > 
> > 
> > Vnc
> 
> He (also) asked for a Unix version of chromedriver file. Furthermore, VNC is only a viewer and if the Unix server is a non-GUI version, like Ubuntu Server or CentOS, VNC is completely unuseful.

Then you install Gui 
I did it. Works perfect

**Comment by yoannes** [comment]
Today after the third day I got blocked again for likes.

       |> LIKED 38 images  |  ALREADY LIKED: 2
        |> COMMENTED on 0 images
        |> FOLLOWED 0 users  |  ALREADY FOLLOWED: 0
        |> UNFOLLOWED 0 users
        |> LIKED 0 comments
        |> REPLIED to 0 comments
        |> INAPPROPRIATE images: 0
        |> NOT VALID users: 52

        [Session lasted 24.28 minutes]

**Comment by ghost** [comment]
> Today after the third day I got blocked again for likes.
> 
> ```
>    |> LIKED 38 images  |  ALREADY LIKED: 2
>     |> COMMENTED on 0 images
>     |> FOLLOWED 0 users  |  ALREADY FOLLOWED: 0
>     |> UNFOLLOWED 0 users
>     |> LIKED 0 comments
>     |> REPLIED to 0 comments
>     |> INAPPROPRIATE images: 0
>     |> NOT VALID users: 52
> 
>     [Session lasted 24.28 minutes]
> ```

Just for information.
You got blocked after using the customized chromedriver published some days ago here?

**Comment by ghost** [comment]
> > > > What to do on unix server ? We can't use headless=false
> > > > is there a version of the chromedriver for unix ? as mentioned is for windows
> > > 
> > > 
> > > > What to do on unix server ? We can't use headless=false
> > > > is there a version of the chromedriver for unix ? as mentioned is for windows
> > > 
> > > 
> > > Vnc
> > 
> > 
> > He (also) asked for a Unix version of chromedriver file. Furthermore, VNC is only a viewer and if the Unix server is a non-GUI version, like Ubuntu Server or CentOS, VNC is completely unuseful.
> 
> Then you install Gui
> I did it. Works perfect
Most of servers run non-GUI, CentOS is only non-GUI and Ubuntu (non server edition) is not optimized to run on servers.

**Comment by Tr1pke** [comment]
> > > > What to do on unix server ? We can't use headless=false
> > > > is there a version of the chromedriver for unix ? as mentioned is for windows
> > > 
> > > 
> > > > What to do on unix server ? We can't use headless=false
> > > > is there a version of the chromedriver for unix ? as mentioned is for windows
> > > 
> > > 
> > > Vnc
> > 
> > 
> > He (also) asked for a Unix version of chromedriver file. Furthermore, VNC is only a viewer and if the Unix server is a non-GUI version, like Ubuntu Server or CentOS, VNC is completely unuseful.
> 
> Then you install Gui
> I did it. Works perfect
> Most of servers run non-GUI, CentOS is only non-GUI and Ubuntu (non server edition) is not optimized to run on servers.

Then don’t be surprised if you get blocked my bot is running on 6 accounts for almost 2 weeks. Without any block. I like comment follow and unfollow 
I installed a GUI and never had any problem anymore

**Comment by ghost** [comment]
> > > > > What to do on unix server ? We can't use headless=false
> > > > > is there a version of the chromedriver for unix ? as mentioned is for windows
> > > > 
> > > > 
> > > > > What to do on unix server ? We can't use headless=false
> > > > > is there a version of the chromedriver for unix ? as mentioned is for windows
> > > > 
> > > > 
> > > > Vnc
> > > 
> > > 
> > > He (also) asked for a Unix version of chromedriver file. Furthermore, VNC is only a viewer and if the Unix server is a non-GUI version, like Ubuntu Server or CentOS, VNC is completely unuseful.
> > 
> > 
> > Then you install Gui
> > I did it. Works perfect
> > Most of servers run non-GUI, CentOS is only non-GUI and Ubuntu (non server edition) is not optimized to run on servers.
> 
> Then don’t be surprised if you get blocked my bot is running on 6 accounts for almost 2 weeks. Without any block. I like comment follow and unfollow
> I installed a GUI and never had any problem anymore


Ok, bravo!

**Comment by Tachenz** [comment]
Got banned with @sionking chromedriver as well. 

Does anyone know how to run Instapy on mobile emulation of chrome?

**Comment by soldiersebas** [comment]
Si se ejecuta de manera local no esta recibiendo los bloques, el problema esta si se ejecuta desde un servidor ejemplo Linux, porque Instagram esta detectando la Ip de origen de la cuenta vs la Ip de ejecucion,

**Comment by ghost** [comment]
> Got banned with @sionking chromedriver as well.
> 
> Does anyone know how to run Instapy on mobile emulation of chrome?

Banned or blocked on likes? It is a little bit different.

**Comment by yoannes** [comment]
> Si se ejecuta de manera local no esta recibiendo los bloques, el problema esta si se ejecuta desde un servidor ejemplo Linux, porque Instagram esta detectando la Ip de origen de la cuenta vs la Ip de ejecucion,

I'm running on my local computer not even headless and getting blocked..

**Comment by rvoets** [comment]
I got blocked on likes again in the 3rd cycle (using the customized chrome driver and custom delays). Now when I try to run a new cycle I get blocked after 2 likes or so. Guess I'll have to wait again for some days and try again...

**Comment by rvoets** [comment]
> 
> 
> > > > > What to do on unix server ? We can't use headless=false
> > > > > is there a version of the chromedriver for unix ? as mentioned is for windows
> > > > 
> > > > 
> > > > > What to do on unix server ? We can't use headless=false
> > > > > is there a version of the chromedriver for unix ? as mentioned is for windows
> > > > 
> > > > 
> > > > Vnc
> > > 
> > > 
> > > He (also) asked for a Unix version of chromedriver file. Furthermore, VNC is only a viewer and if the Unix server is a non-GUI version, like Ubuntu Server or CentOS, VNC is completely unuseful.
> > 
> > 
> > Then you install Gui
> > I did it. Works perfect
> > Most of servers run non-GUI, CentOS is only non-GUI and Ubuntu (non server edition) is not optimized to run on servers.
> 
> Then don’t be surprised if you get blocked my bot is running on 6 accounts for almost 2 weeks. Without any block. I like comment follow and unfollow
> I installed a GUI and never had any problem anymore

How many likes/comments/follows/unfollows do you perform on average? @Tr1pke

**Comment by Tr1pke** [comment]
> > > > > > What to do on unix server ? We can't use headless=false
> > > > > > is there a version of the chromedriver for unix ? as mentioned is for windows
> > > > > 
> > > > > 
> > > > > > What to do on unix server ? We can't use headless=false
> > > > > > is there a version of the chromedriver for unix ? as mentioned is for windows
> > > > > 
> > > > > 
> > > > > Vnc
> > > > 
> > > > 
> > > > He (also) asked for a Unix version of chromedriver file. Furthermore, VNC is only a viewer and if the Unix server is a non-GUI version, like Ubuntu Server or CentOS, VNC is completely unuseful.
> > > 
> > > 
> > > Then you install Gui
> > > I did it. Works perfect
> > > Most of servers run non-GUI, CentOS is only non-GUI and Ubuntu (non server edition) is not optimized to run on servers.
> > 
> > 
> > Then don’t be surprised if you get blocked my bot is running on 6 accounts for almost 2 weeks. Without any block. I like comment follow and unfollow
> > I installed a GUI and never had any problem anymore
> 
> How many likes/comments/follows/unfollows do you perform on average? @Tr1pke

250 likes, 200 comments 65 follows 100unfollows 
that's my max with supervisor 24/7

**Comment by Tachenz** [comment]
> > > > > What to do on unix server ? We can't use headless=false
> > > > > is there a version of the chromedriver for unix ? as mentioned is for windows
> > > > 
> > > > 
> > > > > What to do on unix server ? We can't use headless=false
> > > > > is there a version of the chromedriver for unix ? as mentioned is for windows
> > > > 
> > > > 
> > > > Vnc
> > > 
> > > 
> > > He (also) asked for a Unix version of chromedriver file. Furthermore, VNC is only a viewer and if the Unix server is a non-GUI version, like Ubuntu Server or CentOS, VNC is completely unuseful.
> > 
> > 
> > Then you install Gui
> > I did it. Works perfect
> > Most of servers run non-GUI, CentOS is only non-GUI and Ubuntu (non server edition) is not optimized to run on servers.
> 
> Then don’t be surprised if you get blocked my bot is running on 6 accounts for almost 2 weeks. Without any block. I like comment follow and unfollow
> I installed a GUI and never had any problem anymore

Sorry, which GUI and how do I install it to try?

**Comment by Tr1pke** [comment]
Any GUI. I have gnome

**Comment by Tachenz** [comment]
> Any GUI. I have gnome

I am sorry, I do not understand. You mean GUI for instapy? called Gnome? Can you give a link please?

**Comment by ghost** [comment]
> > Any GUI. I have gnome
> 
> I am sorry, I do not understand. You mean GUI for instapy? called Gnome? Can you give a link please?

He meant an OS with GUI. Unix Servers usually don’t run with GUI. Gnome is the GUI of most Linux distros.
For you I would suggest to create a VM in your host running Ubuntu or so, you’ll get an OS with GUI or at least running InstaPy in a docker container.

**Comment by Tachenz** [comment]
Right. So doing so, helps to instagram not detect Instapy? (as opposed to running it straight on Windows)?

Do you know - why?

**Comment by LexLinux** [comment]
It's not instapy that needs saving, it's the crazy amount of actions new user runs with then complains that they are action blocked!

**Comment by Tachenz** [comment]
@LexLinux I've been using this for more than a year. With similar very MODERATE amount of actions (no more than 100-150 likes per 24 hours). Without any issues. 
Recent changes - get me blocked after 20 likes per 24  hour period (less than 1 like per hour).
If you did not face an issue yourself, don't assume no one else had. If you'd study comments in this and other threads, you'd see the problem is quite real.

Now back to the topic.  @RRphoto Did you try the GUI method? Did that change anything? For Windows users - you think running VM with Ubuntu will change things?

**Comment by LexLinux** [comment]
LOL I was not me saying you do these crazy amounts of actions ... just pointing out that it's mostly new users who are blocked ....I've been running for maybe 2 months and had 1 or 2 issues that was resolved with a quick internet search.
No need to study issues as i've not had many issues myself.
I'm well aware that others are facing blocks .... I do help these users on the daily.

Might be a good idea to add more complexity and randomness to the template my dude :) The more human it looks to the almighty bot catcher the better lol

**Comment by Tachenz** [comment]
Well, I do have it very random already. (like random delay to like it every 1-2 hours on average). This is way too slow for instagram to detect Instapy purely based on the activity. 

And, again, liking from the app is totally fine even from under the same IP (while bot is blocked, without showing “blocked warning”).
Hence, Instagram clearly learned to differentiate between browser based activity and app activity.
Hence this topic was started...

**Comment by jtrieuDev** [comment]
Hi, i tried to delete the cookie file, but after one session, i cannot find it again and delete it, why ?

**Comment by Tachenz** [comment]
@sionking so with the new chromedriver it still does not work sadly. Anything else we can try?

**Comment by Tachenz** [comment]
So I am trying right now with:
mobile_emulation = { "deviceName": "BlackBerry Z30" }
chrome_options.add_experimental_option("mobileEmulation", mobile_emulation)

Instagram gives a message "Add instagram to your home screen" - so it is promising, they think I am on the mobile! :)

Added to browser.py  as @uluQulu suggested once upon a time.
Trying that at very slow speed with @sionking chromedriver75 version

**Comment by Tachenz** [comment]
And I am getting this error. Can anyone help to troubleshoot?
" File "C:\Users\inna\AppData\Local\Programs\Python\Python36\Lib\site-packages\i
nstapy\instapy.py", line 2858, in interact_user_followers
    self.logfolder)
  File "C:\Users\inna\AppData\Local\Programs\Python\Python36\Lib\site-packages\i
nstapy\unfollow_util.py", line 1079, in get_given_user_followers
    logger, logfolder)
  File "C:\Users\inna\AppData\Local\Programs\Python\Python36\Lib\site-packages\i
nstapy\unfollow_util.py", line 807, in get_users_through_dialog
    dialog = browser.find_element_by_xpath(dialog_address)
  File "C:\Users\inna\AppData\Local\Programs\Python\Python36\Lib\site-packages\s
elenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\inna\AppData\Local\Programs\Python\Python36\Lib\site-packages\s
elenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\inna\AppData\Local\Programs\Python\Python36\Lib\site-packages\s
elenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\inna\AppData\Local\Programs\Python\Python36\Lib\site-packages\s
elenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Una
ble to locate element: {"method":"xpath","selector":"//body/div[3]/div/div[2]"}
  (Session info: chrome=75.0.3770.100)
  (Driver info: chromedriver=2.44.609538 (b655c5a60b0b544917107a59d4153d4bf78e1b
90),platform=Windows NT 6.3.9600 x86_64)"

**Comment by GitNees** [comment]
Very odd that when you open normal chrome, you can like the post, instapy couldnt like, opening a new tab in instapy-chrome session, also wouldn't like, normal chrome and firefox works. So what do they actually detect? Some kind of useragent?

**Comment by GitNees** [comment]
I'll add that I fixed it AGAIN, by deleting my cookie, now likes work again.

I added this to my "quickstart" file:

        if os.path.exists("C:/Users/User/InstaPy/logs/yourusername/yourusername_cookie.pkl"):
            os.remove("C:/Users/User/InstaPy/logs/yourusername/yourusername_cookie.pkl")

So every new run, it will create a new cookie. I thought I had it fixed yesterday but after a modification by adding the part to check if the file exists, it didnt delete it the next runs. so likes and follows were blocked again. This explains why other browsers do work.

**Comment by Tr1pke** [comment]
And now Instagram will think you have a new device every few days and will keep an eye on your account. Nobody uses tons of devices for instagram. Delete cookie is the last resort. And a ban is a warning for to many actions. Don’t delete your cookie but adjust your actions

**Comment by GitNees** [comment]
Good point! My actions arent even that high i think. I'll test some more, but 10% follow and like on 250 pictures, is kind of low, no?

**Comment by Tr1pke** [comment]
Once you are blocked you need to rest your account. What works for me on some test accounts is 48hr min and one week to be sure.

**Comment by GitNees** [comment]
Well, blocked on just instpy but not on app or other browsers, odd no? Anyway, its again blocking. Goes really quick.

**Comment by Tachenz** [comment]
I was blocked after 3 likes, after 7 days wait. While in app I can like 40 pics per minute without problem.
Need to figure our how to run this in mobile emulation (see error above)

**Comment by IKDH** [comment]
Lots of Jarvee users (which use mobile emulation) are also having block when they try to follow with the mobile API.

**Comment by Tachenz** [comment]
Well, and I am able to like while loged into instagram on safari from my iphone, under the same IP/network, when Instapy is blocked on the PC... So, I think it is still worth exploring. If anyone can help debug this error with mobile emulation - would be great:https://github.com/timgrossmann/InstaPy/issues/4667

**Comment by ghost** [comment]
After a week working with no issues, again blocked on any platform (local, server, NAS), with chromedriver version published here.
Very disappointing. I must admit that bots are dead for me... Instagram **** DB DP PD.

**Comment by Tachenz** [comment]
So after a week’s break (7 full days of absolutely no Instapy usage) and at the speed of 1 like per 3 (THREE) hours. Instapy got banned after 12 likes.

As always, I can like as much as I want from my phone browser and app, under the same wifi.
If that is not the red flag, I don’t know what is :)

**Comment by Tr1pke** [comment]
With or without headless ?

**Comment by Tachenz** [comment]
Without headless. windows laptop as well

**Comment by Tr1pke** [comment]
Strange. Running 6 accounts 5 follows an hour 40 likes +30 comments an hour and 100 unfollow a day max

I do have to say I have every 12 hours another ip

**Comment by Tachenz** [comment]
Do you run 24/7? How fast do you run (delays?) and how long are the sessions?
What environment?
Can you post your autorun example? Thank you!

**Comment by Tr1pke** [comment]
24/6. Sunday is rest day :-)

**Comment by breuerfelix** [comment]
No mobile emulation will save instapy, but emulating a normal browser will !

For people who are interested in my alpha testing (worked for some people so far) let me now !

PM me on discord felixbreuer#9641 because I need longterm testers (since my account isn't banned)

**Comment by Tachenz** [comment]
@sionking did you give on modifying the chrome-driver to fix that issue?

**Comment by rvoets** [comment]
I sent you a PM on discord @breuerfelix

**Comment by iam4x** [comment]
I have been running my bot for the last 3days without issues with the fix coming https://github.com/timgrossmann/InstaPy/pull/4696

Here are my stats for the last 24h:

![image](https://user-images.githubusercontent.com/893837/61971040-51b61a00-afde-11e9-9714-422449fab088.png)

just wait for new release guys 👍

**Comment by ghost** [comment]
I tried solution proposed at #4696 but it does not work, blocked after 40 likes.

**Comment by Tr1pke** [comment]
After 7 already
And my bot was off for a week

**Comment by Tachenz** [comment]
@iam4x Do you do likes/comments at all or just follow-unfollow? with #4696 solution?

@RRphoto and @Tr1pke you still blocked, did not figure it out with latest fixes to #4696 ?

**Comment by Tr1pke** [comment]
> @iam4x Do you do likes/comments at all or just follow-unfollow? with #4696 solution?
> 
> @RRphoto and @Tr1pke you still blocked, did not figure it out with latest fixes to #4696 ?

My bot is active again since this morning
its just unpredictable ... i have no idea what can cause bans or no bans
i updated instapy when i started my bot i got this: 
We Noticed a New Login, Windows · Chrome · Mycity, Belgium

While running on linux, we will see how long this one lasts

**Comment by iam4x** [comment]
1. Like + follow an user
2. Unfollow someone that was followed 3 days before

![image](https://user-images.githubusercontent.com/893837/62083014-43723300-b256-11e9-9769-56ce68aff84b.png)

**Comment by Tachenz** [comment]
> 1. Like + follow an user
> 2. Unfollow someone that was followed 3 days before
> 
> ![image](https://user-images.githubusercontent.com/893837/62083014-43723300-b256-11e9-9769-56ce68aff84b.png)

Wow, so 1 to 1 ratio. These are very sick stats. And were you banned for liking (or follow) before applying 4696? 
I assume you don't do User-followers method, but working by hashtags?

**Comment by iam4x** [comment]
* Yes I was blocked before like everyone, tried to figure it out with @breuerfelix who found a really smart way to hide chrome with a mitm proxy and now it's working good for me 👏 
* It's a bit more complex, I have a db of influencers and I will follow their followers when I match a follower with more than 3 relationships with the influencers I track. Like that I have a really good ratio of follow back:

![image](https://user-images.githubusercontent.com/893837/62083887-3d7d5180-b258-11e9-86bc-2805b7e71e63.png)

**Comment by Tachenz** [comment]
I am doing something similar actually. But do you use get_user_followers in instapy for that?

Anyway, I tried his approach and it would not let me even log in for some reason:
![Untitled](https://user-images.githubusercontent.com/36073534/62087366-c3ea6100-b261-11e9-8ece-cb7287b2198e.jpg)

**Comment by Tachenz** [comment]
PS These reporting graphs are amazing :)

**Comment by Tachenz** [comment]
> * Yes I was blocked before like everyone, tried to figure it out with @breuerfelix who found a really smart way to hide chrome with a mitm proxy and now it's working good for me 👏
> * It's a bit more complex, I have a db of influencers and I will follow their followers when I match a follower with more than 3 relationships with the influencers I track. Like that I have a really good ratio of follow back:
> 
> ![image](https://user-images.githubusercontent.com/893837/62083887-3d7d5180-b258-11e9-86bc-2805b7e71e63.png)

So @iam4x do you use session.interact_user_followers  for your quickstart?  

it always gives me either "Failed to load desired amount of users" or  "grabbed 0 followers to interact with" message with this build.

What happens in Firefox it gets to the window with "Suggestions" - down to the button of "See all suggestions" (after clicking on someone else followers list) and just gets stuck there
