### ISSUE TITLE
Failed to get followers count / Unable to save account progress

### ISSUE THREAD

**Issue by carrasboy** [InstaPy/InstaPy#6615]
I use instapy everyday since a few months but got this error this morning, any clue on how to fix it? Many thanks!

<img width="572" alt="screen" src="https://user-images.githubusercontent.com/91972147/171569774-751de7cb-86c0-4b60-91e4-80ed2461e268.png">

**Comment by MastaMack** [comment]
Have the same issue since this morning ☝🏼

**Comment by rdxshubham** [comment]
Same issue since morning!

**Comment by Vaytrex** [comment]
+1 for this issue

**Comment by ticmali** [comment]
i m getting same error.. need help.Thank you

**Comment by gapou** [comment]
+1 for this issue

**Comment by skoenig** [comment]
+1
The `window._sharedData` object does not contain the required data anymore (at least not follower and following counts).

**Comment by voxoff79** [comment]
+1 for the issue

**Comment by yacine-cherif** [comment]
+1 for this issue

**Comment by Revixi** [comment]
Got the same problem

**Comment by Nickhoog** [comment]
Same issue..

**Comment by hasangurlek** [comment]
Class names in xpath_compile.py are no longer valid (eg; topCount_elements g47SY -> _ac2a)

**Comment by yacine-cherif** [comment]
> Class names in xpath_compile.py are no longer valid (eg; topCount_elements g47SY -> _ac2a)

Hello Hasan, Im new at instapy and i dont know the css organisaion/modification made by instagram. Could you please share the new class name please thanks @hasangurlek

**Comment by Revixi** [comment]
@hasangurlek tried that too but I get another error with window.sharedData being undefined ? this it work for you?

**Comment by bittradevid** [comment]
Same Issue

**Comment by voxoff79** [comment]
Great @timgrossmann any guidance? :)

**Comment by wolf2000-hub** [comment]
Same Issue

**Comment by carrasboy** [comment]
This is so sad we have to give up on instapy, I hope a fix will be found by someone here!

**Comment by kenpyfin** [comment]
Same here +1

**Comment by LovanDog** [comment]
same issue

**Comment by WalnutNinja01** [comment]
is the developer still active? Would like to see this fixed please

**Comment by Crixoman** [comment]
Same issue, +1

**Comment by Voltuck** [comment]
Same problem here, when can we expect a fix for this?

**Comment by MastaMack** [comment]
Thank you @S-i-m-o-n-A-I for taking your time!

I implemented the new rountine but running into a circular import right now. But I dont know how to fix this. Probably a minor issue, maybe someone can help. Thanks in advance :)

### Traceback (most recent call last):
  File "C:\Users\Tommi\Desktop\botqutu.py", line 1, in <module>
    from instapy import InstaPy
  File "C:\Users\Tommi\AppData\Local\Programs\Python\Python310\lib\site-packages\instapy\__init__.py", line 6, in <module>
    from .instapy import InstaPy
  File "C:\Users\Tommi\AppData\Local\Programs\Python\Python310\lib\site-packages\instapy\instapy.py", line 35, in <module>
    from .browser import close_browser, set_selenium_local_session
  File "C:\Users\Tommi\AppData\Local\Programs\Python\Python310\lib\site-packages\instapy\browser.py", line 14, in <module>
    from .util import interruption_handler
  File "C:\Users\Tommi\AppData\Local\Programs\Python\Python310\lib\site-packages\instapy\util.py", line 47, in <module>
    from .xpath import read_xpath
  File "C:\Users\Tommi\AppData\Local\Programs\Python\Python310\lib\site-packages\instapy\xpath.py", line 1, in <module>
    from .xpath_compile import xpath
  File "C:\Users\Tommi\AppData\Local\Programs\Python\Python310\lib\site-packages\instapy\xpath_compile.py", line 16, in <module>
    from .comment_util import open_comment_section
  File "C:\Users\Tommi\AppData\Local\Programs\Python\Python310\lib\site-packages\instapy\comment_util.py", line 23, in <module>
    from .util import (
ImportError: cannot import name 'click_element' from partially initialized module 'instapy.util' (most likely due to a circular import) (C:\Users\Tommi\AppData\Local\Programs\Python\Python310\lib\site-packages\instapy\util.py)

**Comment by voxoff79** [comment]
Hi @MastaMack and @S-i-m-o-n-A-I 
Any luck on your workarounds? 

Thank in advance!

**Comment by elouahidiahmed** [comment]
I've got the same issue

**Comment by Remi13Git** [comment]
@timgrossmann become our hero and do your comeback 🤣

**Comment by hasangurlek** [comment]
https://stackoverflow.com/a/72513029
https://stackoverflow.com/a/72533638

**Comment by PashaGV** [comment]
So, no ideas how to solve it?

**Comment by xProSen** [comment]
any fix for this?

**Comment by adrianvignolo** [comment]
I think it was a considerable change in the instagram code structure. Was trying to fix it but, it will need time and a lot of testing so I suppose we will have to expect for the instapy developer to fix it.

**Comment by kelvin-tran** [comment]
Not quite sure how to fix the missing window._sharedData but adding the div before the span seems to fix the xpath lookups to get follower/following counts.

That doesn't fix it entirely though as the code to get the n posts depends on the window._sharedData object as others hve mentioned. Could change that code to do xpath lookup as well probably

**Comment by HilaliAhmer** [comment]
+1 for this issue

**Comment by alexandertomsovic** [comment]
+1 for this issue

**Comment by Diablica15** [comment]
hey man +1

**Comment by rrsconsulting** [comment]
I just found InstaPy I could´t use it yet because of this error, as far as I read it looks it will take time to fix and modify all new instagram xpaths. I'm going to take a look on this issue, if I found something I'll post it.

**Comment by HeIIow2** [comment]
+1 for the issue

**Comment by patgratt** [comment]
godspeed to those with the capabilities to try to fix this

**Comment by s4gor** [comment]
any update?

**Comment by adrielkirch** [comment]
Same here +1

**Comment by alex-wahl** [comment]
+ 1

**Comment by William-Bohm** [comment]
Update on solutions:
@S-i-m-o-n-A-I has come up with a partial solution by using XPATH rather than graphAPI to find data:
https://github.com/InstaPy/InstaPy/issues/6615#issuecomment-1147301248
*(just click on his provided code and replace what's designated to be replaced)*

I'm going to familiarize myself with the InstaPy codebase this weekend and attempt a solution. 
wish me luck! :)

**Comment by HilaliAhmer** [comment]
> Update on solutions: @S-i-m-o-n-A-I has come up with a partial solution by using XPATH rather than graphAPI to find data: [#6615 (comment)](https://github.com/InstaPy/InstaPy/issues/6615#issuecomment-1147301248) _(just click on his provided code and replace what's designated to be replaced)_
> 
> I'm going to familiarize myself with the InstaPy codebase this weekend and attempt a solution. wish me luck! :)

Not work... ""pandas ??""

Traceback (most recent call last):
  File ".\InstaPy\quickstart.py", line 4, in <module>
    from instapy import InstaPy
  File ".\InstaPy\instapy\__init__.py", line 6, in <module>
    from .instapy import InstaPy
  File ".\InstaPy\instapy\instapy.py", line 18, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'

**Comment by Gustavosta** [comment]
Same Issue :/

**Comment by NomanBaigA** [comment]
> > Update on solutions: @S-i-m-o-n-A-I has come up with a partial solution by using XPATH rather than graphAPI to find data: [#6615 (comment)](https://github.com/InstaPy/InstaPy/issues/6615#issuecomment-1147301248) _(just click on his provided code and replace what's designated to be replaced)_
> > I'm going to familiarize myself with the InstaPy codebase this weekend and attempt a solution. wish me luck! :)
> 
> Not work... ""pandas ??""
> 
> Traceback (most recent call last): File ".\InstaPy\quickstart.py", line 4, in from instapy import InstaPy File ".\InstaPy\instapy__init__.py", line 6, in from .instapy import InstaPy File ".\InstaPy\instapy\instapy.py", line 18, in import pandas as pd ModuleNotFoundError: No module named 'pandas'

pip install pandas

**Comment by NomanBaigA** [comment]
> Update on solutions: @S-i-m-o-n-A-I has come up with a partial solution by using XPATH rather than graphAPI to find data: [#6615 (comment)](https://github.com/InstaPy/InstaPy/issues/6615#issuecomment-1147301248) _(just click on his provided code and replace what's designated to be replaced)_
> 
> I'm going to familiarize myself with the InstaPy codebase this weekend and attempt a solution. wish me luck! :)


I tried it 2 times but I got an issue -

INFO [2022-06-26 13:02:38] [USERNAME]  Logged in successfully!
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
INFO [2022-06-26 13:02:38] [USERNAME]  Saving account progress...
WARNING [2022-06-26 13:02:43] [USERNAME]  Unable to save account progress, skipping data update
        b"'NoneType' object has no attribute 'get'"

INFO [2022-06-26 13:02:45] [USERNAME]  Sessional Live Report:
        |> No any statistics to show


[Session lasted 1.52 minutes]
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2022-06-26 13:02:45] [USERNAME]  Session ended!
oooooooooooooooooooooooooooooooooooooooooooooooooooooooo



Traceback (most recent call last):
  File "C:\Users\USERNAME\Desktop\instapy-quickstart-master\quickstart_templates\basic_follow-unfollow_activity.py", line 35, in <module>
    with smart_run(session):
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python310\lib\site-packages\instapy\util.py", line 1983, in smart_run
    session.login()
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python310\lib\site-packages\instapy\instapy.py", line 477, in login
    self.followed_by = log_follower_num(self.browser, self.username, self.logfolder)
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python310\lib\site-packages\instapy\print_log_writer.py", line 21, in log_follower_num
    followed_by = getUserData("graphql.user.edge_followed_by.count", browser)
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python310\lib\site-packages\instapy\util.py", line 501, in getUserData
    get_key = shared_data.get("entry_data").get("ProfilePage")
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by HilaliAhmer** [comment]
> Çözümlerle ilgili güncelleme: @S-i-m-o-n-A-Iverileri bulmak için graphAPI yerine XPATH kullanarak kısmi bir çözüm buldu: [#6615 (yorum) ](https://github.com/InstaPy/InstaPy/issues/6615#issuecomment-1147301248) _(sadece sağlanan kodu tıklayın ve değiştirilmek üzere belirlenmiş olanı değiştirin)_
> 
> Bu hafta sonu InstaPy kod tabanını tanıyacağım ve bir çözüm deneyeceğim. bana şans Dile! :)


I got an issue one more..


InstaPy Version: 0.6.16
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.
Workspace in use: "C:/Users/insta-USERNAME/InstaPy"
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2022-06-26 12:01:28] [insta-USERNAME]  Session started!
oooooooooooooooooooooooooooooooooooooooooooooooooooooo
INFO [2022-06-26 12:01:35] [insta-USERNAME]  - Cookie file for user 'insta-USERNAME' loaded...
..................................................................
INFO [2022-06-26 12:02:02] [insta-USERNAME]  Logged in successfully!
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
INFO [2022-06-26 12:02:02] [insta-USERNAME]  Saving account progress...
WARNING [2022-06-26 12:02:05] [insta-USERNAME]  Unable to save account progress, skipping data update
        b"'NoneType' object has no attribute 'get'"

INFO [2022-06-26 12:02:06] [insta-USERNAME]  Sessional Live Report:
        |> No any statistics to show


[Session lasted 44.75 seconds]
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2022-06-26 12:02:06] [insta-USERNAME]  Session ended!
ooooooooooooooooooooooooooooooooooooooooooooooooooooooooo



Traceback (most recent call last):
  File "C:\Users\insta-USERNAME\Desktop\PANDAS\InstaPy\quickstart.py", line 17, in <module>
    with smart_run(session):
  File "C:\Program Files\Python310\lib\contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "C:\Users\insta-USERNAME\Desktop\PANDAS\InstaPy\instapy\util.py", line 1983, in smart_run
    session.login()
  File "C:\Users\insta-USERNAME\Desktop\PANDAS\InstaPy\instapy\instapy.py", line 477, in login
    self.followed_by = log_follower_num(self.browser, self.username, self.logfolder)
  File "C:\Users\insta-USERNAME\Desktop\PANDAS\InstaPy\instapy\print_log_writer.py", line 21, in log_follower_num
    followed_by = getUserData("graphql.user.edge_followed_by.count", browser)
  File "C:\Users\insta-USERNAME\Desktop\PANDAS\InstaPy\instapy\util.py", line 501, in getUserData
    get_key = shared_data.get("entry_data").get("ProfilePage")
AttributeError: 'NoneType' object has no attribute 'get'
PS C:\Users\insta-USERNAME\Desktop\PANDAS\InstaPy>

**Comment by aru12** [comment]
The problem is that the URL `https://www.instagram.com/${usrname}/` is open at the relevant location.
But I don't know how to fix it.

**Comment by matcode1** [comment]
Hello all, 

First of all, I want to thank @timgrossmann for his excellent job in this project, from which many of us have benefit.

Second, @S-i-m-o-n-A-I has make quite a few advances to solve this issue, I have been working with his pull request for a couple days.

I have managed to perform a partial workaround (at least now "liking" works). I do not even want to make a pull request because the code is still quite c
[modified_files.zip](https://github.com/InstaPy/InstaPy/files/9023582/modified_files.zip)
rappy.

Please find attached the files that I have modified.

Keep up the good work fellows!!

**Comment by MastaMack** [comment]
> Hello all,
> 
> First of all, I want to thank @timgrossmann for his excellent job in this project, from which many of us have benefit.
> 
> Second, @S-i-m-o-n-A-I has make quite a few advances to solve this issue, I have been working with his pull request for a couple days.
> 
> I have managed to perform a partial workaround (at least now "liking" works). I do not even want to make a pull request because the code is still quite c [modified_files.zip](https://github.com/InstaPy/InstaPy/files/9023582/modified_files.zip) rappy.
> 
> Please find attached the files that I have modified.
> 
> Keep up the good work fellows!!

I implemented your new code but liking doesn't work. 

INFO [2022-07-01 10:49:13] [u]  Like# [1/20]
INFO [2022-07-01 10:49:13] [u]  https://www.instagram.com/p/CfdqfsyIWno/
WARNING [2022-07-01 10:49:17] [u]  Additional data from page not loaded, need to extract via xpath: b'https://www.instagram.com/p/CfdqfsyIWno/'
INFO [2022-07-01 10:49:17] [u]  Image from: b'charlee039'
INFO [2022-07-01 10:49:17] [u]  Image link: b'https://www.instagram.com/p/CfdqfsyIWno/'
INFO [2022-07-01 10:49:17] [u]  Description: b'#Sonnenuntergang in den#Du\xcc\x88nen. #Natur pur \xf0\x9f\xa5\xb0\n#Da\xcc\x88nemark #Vanlife #Reisenmitdemdings #Strand #Nordsee #Urlaub #Camping #Reisen #Erholung#Sonnenuntergang#Du\xcc\x88nen#Natur#Da\xcc\x88nemark#Vanlife#Reisenmitdemdings#Strand#Nordsee#Urlaub#Camping#Reisen#Erholung'
ERROR [2022-07-01 10:49:20] [u]  ~could not check if profile is public or private
INFO [2022-07-01 10:49:20] [u]  --> Sorry, could not check if profile is public or private

Any thoughts or solutions?

**Comment by HilaliAhmer** [comment]
> Kısmi bir geçici çözüm gerçekleştirmeyi başardım (en azından şimdi "beğenme" işe yarıyor).

NOT WORK!

**Comment by matcode1** [comment]
> > Hello all,
> > First of all, I want to thank @timgrossmann for his excellent job in this project, from which many of us have benefit.
> > Second, @S-i-m-o-n-A-I has make quite a few advances to solve this issue, I have been working with his pull request for a couple days.
> > I have managed to perform a partial workaround (at least now "liking" works). I do not even want to make a pull request because the code is still quite c [modified_files.zip](https://github.com/InstaPy/InstaPy/files/9023582/modified_files.zip) rappy.
> > Please find attached the files that I have modified.
> > Keep up the good work fellows!!
> 
> I implemented your new code but liking doesn't work.
> 
> INFO [2022-07-01 10:49:13] [u] Like# [1/20] INFO [2022-07-01 10:49:13] [u] https://www.instagram.com/p/CfdqfsyIWno/ WARNING [2022-07-01 10:49:17] [u] Additional data from page not loaded, need to extract via xpath: b'https://www.instagram.com/p/CfdqfsyIWno/' INFO [2022-07-01 10:49:17] [u] Image from: b'charlee039' INFO [2022-07-01 10:49:17] [u] Image link: b'https://www.instagram.com/p/CfdqfsyIWno/' INFO [2022-07-01 10:49:17] [u] Description: b'#Sonnenuntergang in den#Du\xcc\x88nen. #Natur pur \xf0\x9f\xa5\xb0\n#Da\xcc\x88nemark #Vanlife #Reisenmitdemdings #Strand #Nordsee #Urlaub #Camping #Reisen #Erholung#Sonnenuntergang#Du\xcc\x88nen#Natur#Da\xcc\x88nemark#Vanlife#Reisenmitdemdings#Strand#Nordsee#Urlaub#Camping#Reisen#Erholung' ERROR [2022-07-01 10:49:20] [u] ~could not check if profile is public or private INFO [2022-07-01 10:49:20] [u] --> Sorry, could not check if profile is public or private
> 
> Any thoughts or solutions?

Hi @MastaMack,

You can set in your session conguration the "ignore_private" as false.

As I said, not fully functional. But it likes now.

**Comment by HilaliAhmer** [comment]
> 

anyone example pls @matcode1 for ignore_private=False ?

**Comment by rogersillyface** [comment]
> > > Hello all,
> > > First of all, I want to thank @timgrossmann for his excellent job in this project, from which many of us have benefit.
> > > Second, @S-i-m-o-n-A-I has make quite a few advances to solve this issue, I have been working with his pull request for a couple days.
> > > I have managed to perform a partial workaround (at least now "liking" works). I do not even want to make a pull request because the code is still quite c [modified_files.zip](https://github.com/InstaPy/InstaPy/files/9023582/modified_files.zip) rappy.
> > > Please find attached the files that I have modified.
> > > Keep up the good work fellows!!
> > 
> > 
> > I implemented your new code but liking doesn't work.
> > INFO [2022-07-01 10:49:13] [u] Like# [1/20] INFO [2022-07-01 10:49:13] [u] https://www.instagram.com/p/CfdqfsyIWno/ WARNING [2022-07-01 10:49:17] [u] Additional data from page not loaded, need to extract via xpath: b'https://www.instagram.com/p/CfdqfsyIWno/' INFO [2022-07-01 10:49:17] [u] Image from: b'charlee039' INFO [2022-07-01 10:49:17] [u] Image link: b'https://www.instagram.com/p/CfdqfsyIWno/' INFO [2022-07-01 10:49:17] [u] Description: b'#Sonnenuntergang in den#Du\xcc\x88nen. #Natur pur \xf0\x9f\xa5\xb0\n#Da\xcc\x88nemark #Vanlife #Reisenmitdemdings #Strand #Nordsee #Urlaub #Camping #Reisen #Erholung#Sonnenuntergang#Du\xcc\x88nen#Natur#Da\xcc\x88nemark#Vanlife#Reisenmitdemdings#Strand#Nordsee#Urlaub#Camping#Reisen#Erholung' ERROR [2022-07-01 10:49:20] [u] ~could not check if profile is public or private INFO [2022-07-01 10:49:20] [u] --> Sorry, could not check if profile is public or private
> > Any thoughts or solutions?
> 
> Hi @MastaMack,
> 
> You can set in your session conguration the "ignore_private" as false.
> 
> As I said, not fully functional. But it likes now.

Where would we put it and what would we put?

I have tried:

 skip_private=False 

(after searching for, "ignore_private," and coming up with nothing. 

Full error here at the end before Instapy disconnects:

Traceback (most recent call last):
  File "/Users/roryjmurphy/InstaPy/like_by_tag_interact.py", line 102, in <module>
    session.like_by_tags(random.sample(like_tag_list, 13),
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/instapy/instapy.py", line 2138, in like_by_tags
    self.like_by_users(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/instapy/instapy.py", line 2520, in like_by_users
    links = get_links_for_username(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/instapy/like_util.py", line 482, in get_links_for_username
    is_private = is_private_profile(browser, logger, following_status == "Following")
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/instapy/util.py", line 93, in is_private_profile
    is_private = data["graphql"]["user"]["is_private"]
UnboundLocalError: local variable 'data' referenced before assignment

Thanks!

**Comment by poealone** [comment]
yea this is still a thing, i need help. I've tried everything above.

**Comment by PashaGV** [comment]
> Please find attached the files that I have modified.

Which version of instapy you use?

**Comment by yuni720** [comment]
+1 for this issue

**Comment by metapodcod** [comment]
Will there be a fix for this? @elulcao

**Comment by vnc95** [comment]
> 

i get the pandas in module he does not find

**Comment by rogersillyface** [comment]
> > 
> 
> i get the pandas in module he does not find

Type:

pip install pandas

or

pip3 install pandas

in terminal or whatever the Windows version of that is.

**Comment by atelierdevito** [comment]
+1 
Tried everything above 
Thanks for the work so far

**Comment by Pavankunchala** [comment]
any update on this

**Comment by metapodcod** [comment]
yes, friends, I looked on the internet, instagram graphql has been completely removed. The entire structure of Instapy was built on it, which means all code had to be rewritten. This means the end of instapy, Tim has already stopped taking care of the repo, very few people maintain the repo

We love you so much instapy.
REST IN PEACE instapy

![image](https://user-images.githubusercontent.com/67564813/178817054-4a2b5f9a-c5f5-4ae0-8cb1-3fe1d532f368.png)

**Comment by poealone** [comment]
noooooOOOOOOO

**Comment by skoenig** [comment]
Yes, the project looks pretty abandoned, but it is not over. One possibility would be to create a fork and continue all development and all bugfixing there. 
This would only require (ideally several) people who know Python and have the time to regularly look at the PRs, test them, maintain the code...

**Comment by rdxshubham** [comment]
I have recently moved to instagrapi (https://adw0rd.github.io/instagrapi/). These have most of the endpoints working. It's just you have to build up your own bot on top of those wrappers. Yes, it's not as smart as InstaPy, but not bad as well. I have been working on it now for a month and it seems all good to me.

**Comment by mifi** [comment]
My project [instauto](https://github.com/mifi/instauto) and its UI [SimpleInstaBot](https://github.com/mifi/SimpleInstaBot) still works, although not as feature rich as instaPy.

**Comment by denstream-io** [comment]
> My project [instauto](https://github.com/mifi/instauto) and its UI [SimpleInstaBot](https://github.com/mifi/SimpleInstaBot) still works, although not as feature rich as instaPy.

I love InstaPy, but if you need helping hand to make yours feature rich, I would like to join

**Comment by mifi** [comment]
PRs for new features are welcome!

**Comment by denstream-io** [comment]
> It's just you have to build up your own bot on top of those wrappers

How is this different from InstaPy? Not sure I understand well, on instaPy you still have to build your Bot after reading the doc usage, how is instagraphi different in terms of  "building your bot on wrappers"?

**Comment by pedrobart** [comment]
**still `d34d `**

**Comment by DieselYT** [comment]
+1

**Comment by metapodcod** [comment]
Most of the problems seem to be solved here, I sent her an e-mail, I hope there will be a quick return .. https://twitter.com/antique_codes/status/1556935924369436673
https://github.com/official-antique/InstaPy/commit/b52507247af03ffbeb84b7efc364f8531edec605

**Comment by lotrlol** [comment]
oh my god! Please let me know if you get it running again.. I am in dying need of Instapy rn lol

**Comment by jayeshjain18** [comment]
yess! please solve this issue!

**Comment by metapodcod** [comment]
> Should we pin a message that things are currently out of order on the project's main page?

yes this problem has not been solved for a long time

> Most of the problems seem to be solved here, I sent her an e-mail, I hope there will be a quick return .. https://twitter.com/antique_codes/status/1556935924369436673 [official-antique@b525072](https://github.com/official-antique/InstaPy/commit/b52507247af03ffbeb84b7efc364f8531edec605)

For some reason, he deleted the repo after I sent him an e-mail. I guess he didn't want anyone to see

**Comment by lotrlol** [comment]
Yeah i noticed this morning.

I copied the changes from the push last night and the problem was fixed. However, as expected new problems did arise of which i have absolutely no clue how to fix it. So i guess its back to playing the wait&pray game

**Comment by metapodcod** [comment]
> Yeah i noticed this morning.
> 
> I copied the changes from the push last night and the problem was fixed. However, as expected new problems did arise of which i have absolutely no clue how to fix it. So i guess its back to playing the wait&pray game

[antique_codes](https://twitter.com/antique_codes) are you ?

**Comment by Tr1pke** [comment]
same here

**Comment by official-antique** [comment]
Did not see myself tagged here sorry @metapodcod, I'm new to the whole contributing to GitHub stuff so wanted to keep everything clean and have a habit of deleting everything to do so. I've now reuploaded my InstaPy fork with basic changes (the emoji fix) and do still have the new xpath changes to add.

Everyone already knows about the _sharedData not being in the window anymore which is the main issue as far as I can see, it may be somewhere else or need to be rewritten around.

**Comment by metapodcod** [comment]
> Did not see myself tagged here sorry @metapodcod, I'm new to the whole contributing to GitHub stuff so wanted to keep everything clean and have a habit of deleting everything to do so. I've now reuploaded my InstaPy fork with basic changes (the emoji fix) and do still have the new xpath changes to add.
> 
> Everyone already knows about the _sharedData not being in the window anymore which is the main issue as far as I can see, it may be somewhere else or need to be rewritten around.

@official-antique  anyone forking this repo is only sending single data, so it doesn't work anymore. Without this data you cannot see the shared_data data. the repository you deleted had more changes, i saw.  _sharedData is reachable but you must send some values

```
REQUEST_HEADERS = {
    "X-IG-App-Locale": "en_US",
    "X-IG-Device-Locale": "en_US",
    "X-IG-Mapped-Locale": "en_US",
    "X-Pigeon-Session-Id": "d0a3c6b0-24fd-428c-9d20-624a839f7f08",
    "X-Pigeon-Rawclienttime": str(round(time.time() * 1000)),
    "X-IG-Connection-Speed": "-1kbps",
    "X-IG-Bandwidth-Speed-KBPS": str(random.randint(7000, 10000)),
    "X-IG-Bandwidth-TotalBytes-B": str(random.randint(500000, 900000)),
    "X-IG-Bandwidth-TotalTime-MS": str(random.randint(50, 150)),
    "X-IG-App-Startup-Country": "US",
    "X-Bloks-Version-Id": "0a3ae4c88248863609c67e278f34af44673cff300bc76add965a9fb036bd3ca3",
    "X-IG-WWW-Claim": "hmac.AR1ETv6FsubYON5DwNj_0CLNmbW7hSNR1yIMeXuhHJORN4n7",
    "X-Bloks-Is-Layout-RTL": "false",
    "X-Bloks-Enable-RenderCore": "false",
    "X-IG-Connection-Type": "WIFI",
    "X-IG-Capabilities": "3brTvwM=",
    "X-IG-App-ID": "567067343352427",
    "Accept-Language": "en-US",
    "Content-Type": "application/x-www-form-urlencoded; charset=UTF-8",
    "Accept-Encoding": "gzip, deflate",
    "Host": "i.instagram.com",
    "X-FB-HTTP-Engine": "Liger",
    "Connection": "close",
    "X-IG-Prefetch-Request": "foreground",
}
```

you can't send that much value to selenium and selenium-wire, because it is not capable. When you use request library, you can block by api, because we are throwing request for every action. https://github.com/InstaPy/InstaPy/issues/6615#issuecomment-1183603187  As I said here, instapy needs to be rewritten, otherwise everyone will be stuck somewhere. I've been following for about 3 months, no progress. here is a working example for you

```
import hashlib
import hmac
import json
import random
import time
import urllib
import uuid

import requests

SIG_KEY_VERSION = "4"
IG_SIG_KEY = "46024e8f31e295869a0e861eaed42cb1dd8454b55232d85f6c6764365079374b"

USER_AGENT = "Instagram 136.0.0.34.124 Android (23/6.0.1; 640dpi; 1440x2560; ZTE; ZTE A2017U; ailsa_ii; qcom; en_US; 208061712)"
REQUEST_HEADERS = {
    "X-IG-App-Locale": "en_US",
    "X-IG-Device-Locale": "en_US",
    "X-IG-Mapped-Locale": "en_US",
    "X-Pigeon-Session-Id": "d0a3c6b0-24fd-428c-9d20-624a839f7f08",
    "X-Pigeon-Rawclienttime": str(round(time.time() * 1000)),
    "X-IG-Connection-Speed": "-1kbps",
    "X-IG-Bandwidth-Speed-KBPS": str(random.randint(7000, 10000)),
    "X-IG-Bandwidth-TotalBytes-B": str(random.randint(500000, 900000)),
    "X-IG-Bandwidth-TotalTime-MS": str(random.randint(50, 150)),
    "X-IG-App-Startup-Country": "US",
    "X-Bloks-Version-Id": "0a3ae4c88248863609c67e278f34af44673cff300bc76add965a9fb036bd3ca3",
    "X-IG-WWW-Claim": "hmac.AR1ETv6FsubYON5DwNj_0CLNmbW7hSNR1yIMeXuhHJORN4n7",
    "X-Bloks-Is-Layout-RTL": "false",
    "X-Bloks-Enable-RenderCore": "false",
    "X-IG-Connection-Type": "WIFI",
    "X-IG-Capabilities": "3brTvwM=",
    "X-IG-App-ID": "567067343352427",
    "Accept-Language": "en-US",
    "Content-Type": "application/x-www-form-urlencoded; charset=UTF-8",
    "Accept-Encoding": "gzip, deflate",
    "Host": "i.instagram.com",
    "X-FB-HTTP-Engine": "Liger",
    "Connection": "close",
    "X-IG-Prefetch-Request": "foreground",
}

print(REQUEST_HEADERS)


def create_session(cookies=None):
    session = requests.session()
    session.headers.update(REQUEST_HEADERS)
    session.headers.update({"User-Agent": USER_AGENT})

    if cookies:
        session.cookies.update(cookies)
        print("update cookies")
    # else:
    #     session.cookies.clear(cookies)
    #     print("wtf cookies")
    #     exit()

    return session


def get_seed(*args):
    m = hashlib.md5()
    m.update(b"".join([arg.encode("utf-8") for arg in args]))

    return m.hexdigest()


def generate_device_id(seed):
    volatile_seed = "12345"
    m = hashlib.md5()
    m.update(seed.encode("utf-8") + volatile_seed.encode("utf-8"))

    return "android-" + m.hexdigest()[:16]


def generate_signature(data):
    body = (
        hmac.new(
            IG_SIG_KEY.encode("utf-8"), data.encode("utf-8"), hashlib.sha256
        ).hexdigest()
        + "."
        + urllib.parse.quote(data)
    )
    signature = f"signed_body={body}&ig_sig_key_version={SIG_KEY_VERSION}"

    return signature


def login(username, password):
    phone_id = str(uuid.uuid4())
    _uuid = str(uuid.uuid4())

    device_id = generate_device_id(get_seed(username, password))

    session = create_session()
    r = requests.get("https://www.instagram.com/")
    csrftoken = r.cookies["csrftoken"]

    data = json.dumps(
        {
            "jazoest": str(random.randint(22000, 22999)),
            "country_codes": '[{"country_code":"1","source":["default"]}]',
            "phone_id": phone_id,
            "_csrftoken": csrftoken,
            "username": username,
            "adid": "",
            "guid": _uuid,
            "device_id": device_id,
            "google_tokens": "[]",
            "password": password,
            "login_attempt_count": "1",
        }
    )

    post = generate_signature(data)

    response = session.post("https://i.instagram.com/api/v1/accounts/login/", data=post)
    json_data = response.json()

    if json_data.get("status") == "ok":
        return session.cookies

    else:
        return False


def get_user_id(username, session):
    url = f"https://i.instagram.com/api/v1/users/{username}/usernameinfo/"
    res = session.get(url)

    json_data = res.json()

    return json_data["user"]["pk"]


def get_followers(user_id, _uuid, session):
    url = f"https://i.instagram.com/api/v1/friendships/{user_id}/followers/"
    max_id = " "
    usernames = []

    while max_id:
        if max_id and not max_id.isspace():
            payload = {"rank_token": f"{user_id}_{_uuid}", "max_id": max_id}
        else:
            payload = {"rank_token": f"{user_id}_{_uuid}"}

        res = session.get(url, params=payload)

        json_data = res.json()
        users = json_data["users"]

        for user in users:
            usernames.append(user["username"])

        max_id = json_data.get("next_max_id", False)

    return usernames


if __name__ == "__main__":
    cookies = login("jonturkmen", "mysecretpassword")

    session = create_session(cookies)
    username = "jonturkmen"

    user_id = get_user_id(username, session)
    _uuid = str(uuid.uuid4())

    followers = get_followers(user_id, _uuid, session)

    with open("followers.txt", "w") as file:
        for username in followers:
            file.write(username + "\n")

```

Although this is very risky, I'm in favor of doing transactions without using any api, maybe it can work a little slow, but it won't cause any problems. It can only be xpath changes :)

**Comment by official-antique** [comment]
@metapodcod

Would wrapping instagrapi be an effective solution? It's obviously not going to be the same as InstaPy but due to the amount of work needed to rewrite it it may be easier.

I'd be interested in working on an alternative with the same features as InstaPy.

**Comment by kharazian** [comment]
this code could return data
    

    browser.get('view-source:'+current_url+'?__a=1&__d=dis')
    text = browser.find_element(By.TAG_NAME, "pre").text
    shared_data = json.loads(re.search("{.*}", text).group())

I think we can use this to rewrite InstaPy. 
Does anyone have any experience of this function?

**Comment by official-antique** [comment]
It's possible that we could use that to replace the sharedData throughout the project.

I'm just unsure how much we'd lose between the change as I've never seen the response for sharedData.

> this code could return data
> 
>     
> 
> 
> 
>     browser.get('view-source:'+current_url+'?__a=1&__d=dis')
> 
>     text = browser.find_element(By.TAG_NAME, "pre").text
> 
>     shared_data = json.loads(re.search("{.*}", text).group())
> 
> 
> 
> I think we can use this to rewrite InstaPy. 
> 
> Does anyone have any experience of this function?

**Comment by YouFoundJK** [comment]
Couldn't we just skip the account follower and other account status and get straight to the engagement automation? Other than the account statistics, what all functionality will we be missing out on?

**Comment by official-antique** [comment]
@YouFoundJK not too sure honestly, I'll look into it a little later tonight and see if we can just remove everything broken

**Comment by official-antique** [comment]
Fixed a bunch of issues on my [fork](https://github.com/official-antique/InstaPy) for anyone wanting to test.

TODO: fix the xpath(s) which are causing "too few images, skipping tag".

@metapodcod @YouFoundJK @kharazian @lotrlol

**Comment by lotrlol** [comment]
Nice going @official-antique !
Do you have any clue if it runs again with your fixes? And if so which parts?

Also i noticed that Insta has become really good at detecting third party software and blocks you immediately..

I just wanted to give you a little heads-up about it before you pour your heart and soul into fixing it.

Besides that, is there anything i can do to assist?

**Comment by official-antique** [comment]
@lotrlol It's still getting stuck at the finding posts by tag (what i'm using to test) but everything else so far is working. It's got a long way though and i'm sure Insta will change things once fixed.

I've also got a test account so no worries if it messes up, can always make/get more.

**Comment by matthewflannery** [comment]
+1

**Comment by matthewflannery** [comment]
> Fixed a bunch of issues on my [fork](https://github.com/official-antique/InstaPy) for anyone wanting to test.
> 
> TODO: fix the xpath(s) which are causing "too few images, skipping tag".
> 
> @metapodcod @YouFoundJK @kharazian @lotrlol

PR?

**Comment by official-antique** [comment]
@matthewflannery i don't believe it's activity maintained in the sense that it'll go anywhere anymore hence why I've not made any PRs.

I'm working on an alternative with as little change as possible using Instagrapi as the core of the project. Instagrapi uses public and private APIs which means Instagram can't just change them randomly like they would with xpaths, html structuring, etc.

**Comment by matthewflannery** [comment]
@official-antique yes, API much better approach.


 It's a shame to see this project die. But  perhaps a refactor is better anyway. I'll check out your project and see where I can contribute. Is it working ATM?

**Comment by official-antique** [comment]
@matthewflannery it is working in terms of getting data but it doesn't comment, like, etc.

I'm going feature by feature so it may be a little slow.

**Comment by metapodcod** [comment]
> @metapodcod
> 
> Would wrapping instagrapi be an effective solution? It's obviously not going to be the same as InstaPy but due to the amount of work needed to rewrite it it may be easier.
> 
> I'd be interested in working on an alternative with the same features as InstaPy.

I gave my opinion on apiler above. The api you mentioned is the unofficial api and they are using the technique I gave above. Do you know what happened to such apis in the past? All of them had to deal with a lot of trouble. https://github.com/mgp25/Instagram-API Again, as I said above, it should be done without api, the future is better, because you are detected and banned very quickly in official APIs. Without the api it runs a bit slow but at least it behaves like a human :)  https://github.com/InstaPy/InstaPy/issues/6615#issuecomment-1250376864

**Comment by SatoshiSavior** [comment]
RIP

**Comment by GedankenMuseum** [comment]
@official-antique Is there anything new???
Im starving for answers.

**Comment by clanglamet** [comment]
has someone succeed to handle this issue ?

**Comment by wftanya** [comment]
Went [with this maintained project ](https://github.com/mifi/SimpleInstaBot) instead for follow automation
